<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The whole schema, on PostgreSQL.
 *
 * The application moved from MySQL to PostgreSQL on 2026-09-12 so that
 * development and production run the same engine (production is Neon, which is
 * Postgres only). The seven MySQL migrations that grew this schema one change
 * at a time - reservation, the legacy `calendar` import, contact details,
 * customer profiles, the dropped per-day cap, email verification, the split
 * name - are in git history; nothing running Postgres ever held any of their
 * intermediate states, so they are replaced by this one statement of where they
 * ended up. The tables come from the entity mapping (doctrine:migrations:diff
 * generated them); `sessions` is the exception, see below.
 *
 * Two things to know before you run it on real data:
 *
 *  - It does not import a 2016 `calendar` table. That import was MySQL-to-MySQL
 *    and lived in the migration chain this replaces. Legacy data now has to be
 *    brought over deliberately; see README.md, "Upgrading an existing 2016
 *    database".
 *  - `sessions` is not an entity. It belongs to PdoSessionHandler, which keeps
 *    signed-in sessions in the database in production because a container
 *    platform's filesystem does not survive a deploy or a scale-to-zero. Its
 *    shape is the one Symfony's handler creates for the pgsql driver; the
 *    handler is only wired in the prod environment, and Doctrine's schema tools
 *    are told to ignore the table (schema_filter in config/packages/doctrine.yaml).
 */
final class Version20260912150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the PostgreSQL schema: accounts, customers, reservations and the session store.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'This application runs on PostgreSQL. The test suite builds its schema from the mapping instead (see .env.test).',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE app_user (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                email VARCHAR(180) NOT NULL,
                first_name VARCHAR(120) NOT NULL,
                middle_name VARCHAR(120) DEFAULT NULL,
                last_name VARCHAR(120) NOT NULL,
                roles JSON NOT NULL,
                password VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                verification_sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_app_user_email ON app_user (email)');

        $this->addSql(<<<'SQL'
            CREATE TABLE customer (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                full_name VARCHAR(120) NOT NULL,
                phone VARCHAR(40) NOT NULL,
                email VARCHAR(180) DEFAULT NULL,
                notes TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_customer_full_name ON customer (full_name)');
        $this->addSql('CREATE INDEX idx_customer_email ON customer (email)');
        $this->addSql('CREATE INDEX idx_customer_phone ON customer (phone)');

        $this->addSql(<<<'SQL'
            CREATE TABLE reservation (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                reserved_on DATE NOT NULL,
                starts_at TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
                details TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                customer_id INT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_reservation_reserved_on ON reservation (reserved_on)');
        $this->addSql('CREATE INDEX idx_reservation_customer ON reservation (customer_id)');
        // RESTRICT, not CASCADE: a profile in use cannot be removed by accident.
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT fk_reservation_customer FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT NOT DEFERRABLE');

        // Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler,
        // pgsql flavour: id, serialised data, lifetime in seconds, last write.
        $this->addSql(<<<'SQL'
            CREATE TABLE sessions (
                sess_id VARCHAR(128) NOT NULL,
                sess_data BYTEA NOT NULL,
                sess_lifetime INTEGER NOT NULL,
                sess_time INTEGER NOT NULL,
                PRIMARY KEY (sess_id)
            )
            SQL);
        $this->addSql('CREATE INDEX sessions_sess_lifetime_idx ON sessions (sess_lifetime)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE sessions');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT fk_reservation_customer');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE app_user');
    }
}
